// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDlX3zvbdXNni_LcCPTqZtn-1EQgjBI2dE',
    appId: '1:244825804946:web:ec61f5b3c82520cd8e164b',
    messagingSenderId: '244825804946',
    projectId: 'cafeapp-c6ef7',
    authDomain: 'cafeapp-c6ef7.firebaseapp.com',
    storageBucket: 'cafeapp-c6ef7.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_qWqFNAc_GPnZtXULy_1FuQSvxJ1hvm8',
    appId: '1:244825804946:android:f01d59e252c54f508e164b',
    messagingSenderId: '244825804946',
    projectId: 'cafeapp-c6ef7',
    storageBucket: 'cafeapp-c6ef7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCDEXC2C55lbc0_aPNdUBXJqgfuv9evv2A',
    appId: '1:244825804946:ios:7bb9f15e0e3080988e164b',
    messagingSenderId: '244825804946',
    projectId: 'cafeapp-c6ef7',
    storageBucket: 'cafeapp-c6ef7.firebasestorage.app',
    iosClientId: '244825804946-un9tvgo43ge8n04l34mmieoe699qnnu4.apps.googleusercontent.com',
    iosBundleId: 'com.example.cafeApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCDEXC2C55lbc0_aPNdUBXJqgfuv9evv2A',
    appId: '1:244825804946:ios:7bb9f15e0e3080988e164b',
    messagingSenderId: '244825804946',
    projectId: 'cafeapp-c6ef7',
    storageBucket: 'cafeapp-c6ef7.firebasestorage.app',
    iosClientId: '244825804946-un9tvgo43ge8n04l34mmieoe699qnnu4.apps.googleusercontent.com',
    iosBundleId: 'com.example.cafeApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDlX3zvbdXNni_LcCPTqZtn-1EQgjBI2dE',
    appId: '1:244825804946:web:5eff2e7857eda9358e164b',
    messagingSenderId: '244825804946',
    projectId: 'cafeapp-c6ef7',
    authDomain: 'cafeapp-c6ef7.firebaseapp.com',
    storageBucket: 'cafeapp-c6ef7.firebasestorage.app',
  );
}
