// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive.dart';
import 'package:cafe_app/hive/hive_adapters.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(AddressModelAdapter());
    registerAdapter(BasketCoffieModelAdapter());
    registerAdapter(CoffieModelAdapter());
    registerAdapter(CoffieNutritionModelAdapter());
    registerAdapter(CoffieRatingModelAdapter());
    registerAdapter(CoffieSizeModelAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(AddressModelAdapter());
    registerAdapter(BasketCoffieModelAdapter());
    registerAdapter(CoffieModelAdapter());
    registerAdapter(CoffieNutritionModelAdapter());
    registerAdapter(CoffieRatingModelAdapter());
    registerAdapter(CoffieSizeModelAdapter());
  }
}
